version: 2

jobs:
  docker-image:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          VER=20180620
          docker login -u donatello -p $DOCKER_PASS
          docker build -t donatello/sqitch:base-${VER} .
          docker tag donatello/sqitch:base-${VER} donatello/sqitch:base

          docker build -t donatello/sqitch:pgsql-${VER} pgsql
          docker push donatello/sqitch:pgsql-${VER}
          docker tag donatello/sqitch:pgsql-${VER} donatello/sqitch:pgsql
          docker push donatello/sqitch:pgsql
          docker tag donatello/sqitch:pgsql-${VER} donatello/sqitch:latest
          docker push donatello/sqitch:latest

workflows:
  version: 2
  build:
    jobs:
      - docker-image
